name: video_processing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - psycopg2
  - boto3
  - tqdm
  - numpy
  - moviepy
  - yt-dlp
  - opencv
  - scikit-learn
  - python-dotenv
  - pip
  - pip:
      - confluent-kafka